name: SCOAPIClient
targets:
  SCOAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [SCOAPIClient]
    info:
      path: ./Info.plist
      version: 1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
