// Configuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

//2020-04-02T21:32:10.930409-04:00
open class Configuration {
	
	// This value is used to configure the date formatter that is used to serialize dates into JSON format. 
	// You must set it prior to encoding any dates, and it will only be read once. 
	@available(*, unavailable, message: "To set a different date format, use CodableHelper.dateFormatter instead.")
    public static var dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZZxxxxx"
}
