//
// InlineResponse2003.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2003: Codable {

    public var count: Int
    public var next: String?
    public var previous: String?
    public var results: [Tag]

    public init(count: Int, next: String?, previous: String?, results: [Tag]) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }

}
