//
// Profile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Profile: Codable {

    public var url: String
    /** A short biography, often including likes and dislikes, accomplishments, etc. Should be several sentences minimum. */
    public var biography: String
    public var avatar: String?
    public var position: String
    public var graduationYear: Int?
    public var user: String

    public init(url: String, biography: String, avatar: String?, position: String, graduationYear: Int?, user: String) {
        self.url = url
        self.biography = biography
        self.avatar = avatar
        self.position = position
        self.graduationYear = graduationYear
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case biography
        case avatar
        case position
        case graduationYear = "graduation_year"
        case user
    }

}
