//
// Section.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Section: Codable {

    public var url: String?
    public var parent: String?
    public var title: String
    public var subsections: [Any]

    public init(url: String?, parent: String?, title: String, subsections: [Any]) {
        self.url = url
        self.parent = parent
        self.title = title
        self.subsections = subsections
    }

}
