//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Tag: Codable {

    public var url: String?
    public var name: String

    public init(url: String?, name: String) {
        self.url = url
        self.name = name
    }

}
