//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable {

    public var id: Int
    public var name: String
    public var profile: Profile

    public init(id: Int, name: String, profile: Profile) {
        self.id = id
        self.name = name
        self.profile = profile
    }

}
