//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable {

    public var url: String?
    public var name: String
    public var profile: Profile

    public init(url: String? = nil, name: String, profile: Profile) {
        self.url = url
        self.name = name
        self.profile = profile
    }

}
